name: Weekly Build

# Run the Weekly on Sundays 8 AM UTC
on: push
  #schedule:
    #- cron: "0 10 * * 4"

jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Prepare Tags
        id: prep
        run: |
          DOCKER_BASE_IMAGE=noobaa/noobaa-base
          DOCKER_BUILDER_IMAGE=noobaa/noobaa-builder
          DOCKER_CORE_IMAGE=noobaa/noobaa-core
          VERSION="${{ steps.date.outputs.date }}"
          echo "::warning ${VERSION}"
          BASE_TAGS="${DOCKER_BASE_IMAGE}:master-:${VERSION}"
          BUILDER_TAGS="${DOCKER_BUILDER_IMAGE}:master-:${VERSION}"
          CORE_TAGS="${DOCKER_CORE_IMAGE}:master-:${VERSION}"
          echo "::warning ${CORE_TAGS}"
          echo ::set-output name=basetags::${BASE_TAGS}
          echo ::set-output name=buildertags::${BUILDER_TAGS}
          echo ::set-output name=coretags::${CORE_TAGS}

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.GHACTIONSDOCKERHUB }} | docker login -u ${{ secrets.GHACTIONSDOCKERHUBNAME }} --password-stdin

      - name: Build & Push Docker Images
        env:
          DOCKERHUB_OWNER: ${{ secrets.GHACTIONSDOCKERHUBNAME }}
        run: |
            make noobaa
            docker tag noobaa ${{ steps.prep.outputs.coretags }}
            docker push ${{ steps.prep.outputs.coretags }}
