name: Weekly Build

# Run the Weekly on Sundays 8 AM UTC
on:
  schedule:
    - cron: "0 10 * * 4"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "name=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=noobaa/noobaa-core
          VERSION=""
          if [ "${{ github.event_name }}" = "schedule" ]; then
            VERSION="master-${{ steps.date.outputs.date }}"
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          echo ::set-output name=tags::${TAGS}

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.GHACTIONSDOCKERHUB }} | docker login -u ${{ secrets.GHACTIONSDOCKERHUBNAME }} --password-stdin

      - name: Build & Push Docker Images
        env:
          DOCKERHUB_OWNER: ${{ secrets.GHACTIONSDOCKERHUBNAME }}
        run: make noobaa \
             docker tag noobaa ${{ steps.prep.outputs.tags }} \
             docker push
